apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
  labels:
    app: rb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rb
  template:
    metadata:
      labels:
        app: rb
    spec:
      containers:
        - name: rb
          image: rabbitmq
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: rmq-pass
                  name: vprosecret
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
